// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0hqZq9O9owjwoEIVrdofSH5172QCTfk4',
    appId: '1:304656874782:web:7fc79865cc8f349d169d0f',
    messagingSenderId: '304656874782',
    projectId: 'vinh-movie-cinema',
    authDomain: 'vinh-movie-cinema.firebaseapp.com',
    storageBucket: 'vinh-movie-cinema.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hqZq9O9owjwoEIVrdofSH5172QCTfk4',
    appId: '1:304656874782:android:8fc48a0ffeb702f9169d0f',
    messagingSenderId: '304656874782',
    projectId: 'vinh-movie-cinema',
    storageBucket: 'vinh-movie-cinema.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0hqZq9O9owjwoEIVrdofSH5172QCTfk4',
    appId: '1:304656874782:ios:8fc48a0ffeb702f9169d0f',
    messagingSenderId: '304656874782',
    projectId: 'vinh-movie-cinema',
    storageBucket: 'vinh-movie-cinema.firebasestorage.app',
    iosBundleId: 'com.example.movieticketbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0hqZq9O9owjwoEIVrdofSH5172QCTfk4',
    appId: '1:304656874782:ios:8fc48a0ffeb702f9169d0f',
    messagingSenderId: '304656874782',
    projectId: 'vinh-movie-cinema',
    storageBucket: 'vinh-movie-cinema.firebasestorage.app',
    iosBundleId: 'com.example.movieticketbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0hqZq9O9owjwoEIVrdofSH5172QCTfk4',
    appId: '1:304656874782:web:7fc79865cc8f349d169d0f',
    messagingSenderId: '304656874782',
    projectId: 'vinh-movie-cinema',
    authDomain: 'vinh-movie-cinema.firebaseapp.com',
    storageBucket: 'vinh-movie-cinema.firebasestorage.app',
  );
}
